[behave]
paths = features
# allows print() outputs to show in console
stdout_capture = false
stderr_capture = false
# useful for debugging Selenium
log_capture = false
#tags = @login
# pretty - console (stdout)
#format = pretty, allure_behave.formatter:AllureFormatter
#outfiles = Reports/logs, Reports/allure-reports


